In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df.drop(['deck' , 'embark_town','alive' , 'class', 'who', 'adult_male'],axis =1 , inplace=True)

In [6]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [7]:
df['age'].fillna(df['age'].mean(), inplace =True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [9]:
df.dropna(subset=['embarked'] , inplace = True)   #drop complete row

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le =LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])   #s=2,c=0,Q=1

In [13]:

df  = df.astype(int)

In [14]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [15]:
x= df.drop("survived" , axis =1)
y=df['survived']   #to predict

In [16]:
from sklearn.model_selection import train_test_split 

x_train , x_test , y_train , y_test  = train_test_split(x,y,test_size=0.20 , random_state=42)

In [17]:
#use logestic regression :-
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression()

model.fit(x_train , y_train )

LogisticRegression()

In [18]:
y_pred = model.predict(x_test)

In [19]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [20]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [21]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [22]:
accuracy_score(y_test , y_pred)

0.8033707865168539

In [23]:
confusion_matrix(y_test , y_pred)

array([[90, 19],
       [16, 53]])

In [24]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

**now make a model using KNN**

wHEN YOU ARE USING KNN IT IS IMPORTANT TO DO FEATURE SCALING :-

In [25]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [26]:
#feature scaling 
x_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
708       1    0   22      0      0   151         2      1
240       3    0   29      1      0    14         0      0
382       3    1   32      0      0     7         2      1
792       3    0   29      8      2    69         2      0
683       3    1   14      5      2    46         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
107       3    1   29      0      0     7         2      1
271       3    1   25      0      0     0         2      1
862       1    0   48      0      0    25         2      1
436       3    0   21      2      2    34         2      0
103       3    1   33      0      0     8         2      1

[711 rows x 8 columns]

In [27]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [28]:
x_train_scaled = scaler.fit_transform(x_train)
x_train_scaled

array([[-1.58410418, -1.40530972, -0.58667407, ...,  2.42752104,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.05336323, ..., -0.35872483,
        -1.95246446, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.17519856, ..., -0.50108776,
         0.58770431,  0.81076671],
       ...,
       [-1.58410418, -1.40530972,  1.39419477, ..., -0.13501166,
         0.58770431,  0.81076671],
       [ 0.8122747 , -1.40530972, -0.66286134, ...,  0.04802639,
         0.58770431, -1.23340042],
       [ 0.8122747 ,  0.71158691,  0.25138582, ..., -0.4807502 ,
         0.58770431,  0.81076671]])

In [29]:
x_test_scaled=scaler.fit_transform(x_test)
x_test_scaled

array([[ 0.87837838,  0.83380939, -0.05614186, ..., -0.48065958,
         0.5836712 ,  0.82416338],
       [-1.52702703, -1.19931487, -1.19358508, ...,  1.70666776,
         0.5836712 , -1.21335165],
       [ 0.87837838, -1.19931487, -1.19358508, ..., -0.40323207,
        -1.88998295, -1.21335165],
       ...,
       [ 0.87837838, -1.19931487,  0.75631758, ..., -0.01609448,
         0.5836712 , -1.21335165],
       [ 0.87837838, -1.19931487,  0.35008786, ..., -0.32580455,
         0.5836712 , -1.21335165],
       [ 0.87837838, -1.19931487, -2.00604452, ..., -0.30644767,
         0.5836712 , -1.21335165]])

In [30]:
from sklearn.neighbors import KNeighborsClassifier
knn_model1 = KNeighborsClassifier(n_neighbors=5)
knn_model1.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [31]:
y_pred_knn = knn_model1.predict(x_test_scaled)

In [32]:
accuracy_score(y_test , y_pred_knn)

0.7808988764044944

In [33]:
confusion_matrix(y_test , y_pred_knn)

array([[90, 19],
       [20, 49]])

In [34]:
print(classification_report(y_test , y_pred_knn))

              precision    recall  f1-score   support

           0       0.82      0.83      0.82       109
           1       0.72      0.71      0.72        69

    accuracy                           0.78       178
   macro avg       0.77      0.77      0.77       178
weighted avg       0.78      0.78      0.78       178

**IMPLEMENTATION OF NAVE BAYES ALGORITHM**

In [35]:
from sklearn.naive_bayes import GaussianNB

In [36]:
model_nb = GaussianNB()

In [37]:
model_nb.fit(x_train,y_train)

GaussianNB()

In [38]:
y_pred_nb = model_nb.predict(x_test)

In [39]:
accuracy_score(y_test , y_pred_nb)

0.7752808988764045

In [40]:
confusion_matrix(y_test , y_pred_nb)

array([[84, 25],
       [15, 54]])

In [41]:
print(classification_report(y_test , y_pred_nb))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178

 **DECISION TREE**

In [42]:
from sklearn.tree import DecisionTreeClassifier

In [43]:
model_dt = DecisionTreeClassifier(random_state= 42)

In [44]:
#FEATURE SCALING IMPORTANT 

model_dt.fit(x_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [45]:
y_pred_dt = model_dt.predict(x_test_scaled)

In [46]:
accuracy_score(y_test , y_pred_dt)

0.7696629213483146

In [47]:
confusion_matrix(y_test , y_pred_dt)

array([[88, 21],
       [20, 49]])

In [48]:
print(classification_report(y_test , y_pred_dt))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81       109
           1       0.70      0.71      0.71        69

    accuracy                           0.77       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.77      0.77      0.77       178

**SUPPORT VECTOR MACHINES (SVM)**

In [49]:
from sklearn.svm import SVC

In [50]:
model_svm = SVC(kernel='rbf')

In [51]:
model_svm.fit(x_train_scaled,y_train)

SVC()

In [52]:
y_pred_svm = model_svm.predict(x_test_scaled)
accuracy_score(y_test , y_pred_svm)

0.8258426966292135

In [53]:
confusion_matrix(y_test , y_pred_svm)

array([[96, 13],
       [18, 51]])

In [54]:
print(classification_report(y_test , y_pred_svm))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       109
           1       0.80      0.74      0.77        69

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178

#let us use cross validation

In [55]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [57]:
x = df.drop('survived' , axis =1)
y = df['survived']

In [58]:
from sklearn.model_selection import cross_val_score

In [62]:
scaaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [63]:
#1. use model svm 
scores = cross_val_score(model_svm,x_scaled,y , cv=5 , scoring="accuracy")   #cv = cross validation

In [64]:
print(scores)

[0.83146067 0.82022472 0.81460674 0.80898876 0.86440678]

In [65]:
#take average of these 
print(scores.mean())

0.8279375357074844

In [66]:
#2. use model knn
scores = cross_val_score(knn_model1,x_scaled,y , cv=5 , scoring="accuracy")
print(scores)
print(scores.mean())

[0.78651685 0.76404494 0.8258427  0.81460674 0.80225989]
0.7986542245921411

In [67]:
#3. use model naive byes
scores = cross_val_score(model_nb,x_scaled,y , cv=5 , scoring="accuracy")
print(scores)
print(scores.mean())

[0.73033708 0.78651685 0.81460674 0.78651685 0.80225989]
0.7840474830191074

In [68]:
#4. use model decision tree
scores = cross_val_score(model_dt,x_scaled,y , cv=5 , scoring="accuracy")
print(scores)
print(scores.mean())

[0.76404494 0.81460674 0.79213483 0.78651685 0.83050847]
0.7975623690725577

In [69]:
#3. use model logestic regression 
scores = cross_val_score(model,x_scaled,y , cv=5 , scoring="accuracy")
print(scores)
print(scores.mean())

[0.7752809  0.78651685 0.78651685 0.78651685 0.82485876]
0.7919380435472609